### ISSUE TITLE
Add the terms of use on the registration form

### ISSUE THREAD

**Issue by marchufschmitt** [InseeFrLab/legacy-onyxia-entrypoint#2]
- [x] Add the terms of use on the registration form (Keycloak and Front)
- [x] Add a function for accept again when we update the terms

**Comment by marchufschmitt** [comment]
<img width="516" alt="Capture d’écran 2021-07-12 à 10 52 24" src="https://user-images.githubusercontent.com/62331119/125259084-49586600-e2ff-11eb-819b-ba7c681c22f4.png">
See the prototype here : https://www.figma.com/file/gbdR2mZSfz8oOUK41T9Se3/Design-System?node-id=197%3A5521

**Comment by garronej** [comment]
> Add a function for accept again when we update the terms  

This can be done, but manually. Meaning that if we update the terms we have to go on keycloak admin console and add a required action to every user: Validata therms of service.

**Comment by garronej** [comment]
> <img alt="Capture d’écran 2021-07-12 à 10 52 24" width="516" src="https://user-images.githubusercontent.com/62331119/125259084-49586600-e2ff-11eb-819b-ba7c681c22f4.png">
> 
> See the prototype here : https://www.figma.com/file/gbdR2mZSfz8oOUK41T9Se3/Design-System?node-id=197%3A5521

I am sorry, I have already spent a lot of time implementing this feature. It was just disabled because we didn't had proper therms of service to display yet but now it's enabled. 
I can't implement it as shown because if we want the TOS to be integrated to Keycloak we have to actually display it. We can't have them just as footnote like that.... Well there is always a way but it would be a hack.  

Here is how it looks today: 

![image](https://user-images.githubusercontent.com/6702424/125278492-1b7d1c80-e313-11eb-9eda-ca5d5c6c50f3.png)

To update the content it's [here](https://github.com/InseeFrLab/onyxia-web/tree/main/src/app/assets/md)
