### ISSUE TITLE
CI: Some runners fail with no apparent reasons

### ISSUE THREAD

**Issue by statnmap** [InseeFrLab/legacy-onyxia-entrypoint#23]
Frequently, the CI runners fail to fetch the current repository, then fail to continue the pipeline.
FAIL  
![Capture d’écran de 2021-07-19 11-25-50](https://user-images.githubusercontent.com/21193866/126138938-1089ebc8-c2f4-4f1a-b767-775e45e1ada2.png)

If I retry, without changing anything in the repository, it may or may not work.
RETRY and FAIL  
![Capture d’écran de 2021-07-19 11-32-12](https://user-images.githubusercontent.com/21193866/126139117-4221c051-6bbc-4479-a8f4-7d7a6424931d.png)

RETRY and WORK  
![Capture d’écran de 2021-07-19 11-35-03](https://user-images.githubusercontent.com/21193866/126139038-9d64c564-3af3-49db-99b7-d27ea4a3bc3d.png)

**Comment by olevitt** [comment]
Thanks for your report !
This issue seems to be about the "sspcloud" specific instance and not about the open-source onyxia project.
Anyway, this seems related to a bug that happens randomly when using kubernetes-based runners. Some users have reported similar issues in the past.
Latest gitlab version may have fixed it by allowing to override the runners support image. But we have not yet upgraded and tested the fix. This operation is currently planned for later this week. I will keep you posted here.

**Comment by olevitt** [comment]
@statnmap we have just upgraded the runners version. It may resolve this issue. Please re-open this issue if that's not the case.
