### ISSUE TITLE
login error after linking onyxia to keycloak

### ISSUE THREAD

**Issue by bbusioc** [InseeFrLab/legacy-onyxia-entrypoint#34]
Hello,

I'm recently facing an error, which I can't understand.
I'm doing the exact steps that I did until now, but now I'm hitting this error after linking onyxia to a keycloak instance.

<pre>
2022-03-21 09:48:20.273 ERROR 1 --- [nio-8080-exec-1] o.k.a.rotation.AdapterTokenVerifier      : Didn't find publicKey for kid: null
</pre>

In my browser with the web developer tools enabled I'm getting this:

![image](https://user-images.githubusercontent.com/100717029/159238738-467e11a2-4ccb-48e5-abfb-1539cf9a1931.png)

It looks like after I push login, it's using a "john doe" jwt token; but I can't figure out if I'm doing something wrong or if anything changed recently that might cause this kind of issue.

Thanks for having a look.

Bogdan

**Comment by olevitt** [comment]
Hi,

It appears the web app thinks you are using no authentication.
Most of the time, this happens if the `KEYCLOAK` prefixed variables are not set (defaulting to dummy auth). Please check you are correctly setting those variables. Check here for a full list of variables : https://github.com/InseeFrLab/onyxia-web/blob/454aa2a7357401562884a5cb17b0e91c6e751199/.env#L6

**Comment by bbusioc** [comment]
thanks. really prompt feedback and support. It works! :)
